#!/bin/bash

set -e

apt-get update && apt-get install -qy couchdb

echo "postfix postfix/main_mailer_type string Internet Site" | debconf-set-selections
echo "postfix postfix/mailname string $(curl https://ip.cozycloud.cc/)" | debconf-set-selections
echo "cozy cozy/fqdn string $(curl https://ip.cozycloud.cc/)" | debconf-set-selections
echo 'cozy cozy/certificate text ' | debconf-set-selections
apt-get install -qy cozy

rm -f /etc/supervisor/conf.d/cozy-init.conf
