#!/bin/bash

set -e

LOCK=/tmp/cozy-init.lock
LOGS=/tmp/post-configuration-cozy.log

if [ -e $LOCK ]; then
	echo 'Already in progress' 2>&1 | tee -a $LOGS
	exit 0
fi

mkdir -p $LOCK

apt-get update

dpkg-reconfigure couchdb 2>&1 | tee -a $LOGS

echo "postfix postfix/main_mailer_type string Internet Site" | debconf-set-selections 2>&1 | tee -a $LOGS
echo "postfix postfix/mailname string $(curl https://ip.cozycloud.cc/)" | debconf-set-selections 2>&1 | tee -a $LOGS
dpkg-reconfigure -u -p high postfix 2>&1 | tee -a $LOGS

echo "cozy cozy/fqdn string $(curl https://ip.cozycloud.cc/)" | debconf-set-selections 2>&1 | tee -a $LOGS
echo 'cozy cozy/certificate text ' | debconf-set-selections 2>&1 | tee -a $LOGS
apt-get install -qy cozy 2>&1 | tee -a $LOGS

echo 'Done' 2>&1 | tee -a $LOGS
sed -i -e '/----------------------/,+5d' /etc/update-motd.d/70-cozy
rmdir $LOCK
mv /etc/supervisor/conf.d/cozy-init.conf /root/
